### ISSUE TITLE
Mixing and matching features

### ISSUE THREAD

**Issue by nmm0** [NimbleSM/NimbleSM#123]
I've recently added some kokkos capabilities to bvh in NimbleSM. However, because bvh is only available in NimbleSM_MPI, the non-contact partions of my runs are not parallelized, causing difficulties with large problems. Additionally, ArborX work has integrated some MPI parts into NimbleSM_Kokkos.

I think it makes sense to unify everything, at least code-wise to avoid tons of duplicated code. For example, a single executable should support both MPI and Kokkos. I think it is still beneficial to be able to generate executables with and without kokkos disabled in the same configuration (just for testing purposes of NGP stuff). Anyway, looking for feedback on this and maybe we can discuss the next meeting. Please feel free to add any suggestions below.

===============================

This is a multistep process

- [x] Merge NimbleSM_serial and NimbleSM_MPI (closed issue #128)
- [x] Refactor NimbleSM_MPI
- [x] Refactor NimbleSM_Kokkos: extract the explicit time integrator (closed issue #133)
- [x] Refactor NimbleSM_Kokkos: keep the host and device vectors in private implementation details (issue #136)
- [x] Refactor MaterialFactory (issue #141)

**Comment by rjones-sandia** [comment]
Reducing cut & paste and ifdef code would make nimble more nimble.

**Comment by uhetmaniuk** [comment]
I think this is a multistep process

- [ ] Merge NimbleSM_serial and NimbleSM_MPI (issue #128)
- [ ] Refactor NimbleSM_Kokkos and NimbleSM_MPI

**Comment by uhetmaniuk** [comment]
@rjones-sandia  @nmm0  @japlews  
Are the executables NimbleSM_Tpetra and NimbleSM_Qthreads actively used?

**Comment by japlews** [comment]
@uhetmaniuk NimbleSM_Tpetra is the only version with an interface to implicit quasistatics, i.e., Trilinos solvers. I believe @rjones-sandia and @hnkolla might be interested in using this? I have never used NimbleSM_Qthreads.

**Comment by nmm0** [comment]
> @rjones-sandia @nmm0 @japlews
> Are the executables NimbleSM_Tpetra and NimbleSM_Qthreads actively used?

I know that QThreads implementation has been a feature for Nimble for a while, but I've never built with it or am aware of a current consumer. Maybe we should ask Dave about it.

**Comment by rjones-sandia** [comment]
?hi

Hemanth and I are marginally interested in the quasistatic capability but haven't used it yet. I think it's protected by benchmarks but looking at the code I wonder how functional it is.


We haven't used the Qthreads variant.


after/during the meeting I can send Dave a checklist of what he would like preserved and what can be omitted at this point.


R


======================================================================
"the second law is just a fancy way of saying things are going from bad to worse" -- Eeyore
"nah, they are just getting more interesting" -- Piglet
======================================================================
Reese Jones (925) 294-4744
________________________________

**Comment by uhetmaniuk** [comment]
Done with #219
